application:
  workspace: DEV
  port: 1023
  ip:

spring:
  config:
    activate:
      on-profile: dev

database:
  url: jdbc:mariadb://localhost:3306/hbd_onf_jswtt
  username:
  password:

logging:
  lovel: DEBUG



